/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/zero/v/zipf/bak/nimcache/stdlib_random.o /home/zero/v/zipf/bak/nimcache/stdlib_random.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg;
struct tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg {
NU64 a0;
NU64 a1;
};
N_NIMCALL(NU64, next_XD15WiThqxScuoeOixQIfg)(tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg* s);
N_NIMCALL(NU64, rotl_YUrTkztAwPd2iMVoSj9bYBw)(NU64 x, NU64 k);
tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg state_4atHrcHUZPts5LqH9bzbl0w;

N_NIMCALL(NU64, rotl_YUrTkztAwPd2iMVoSj9bYBw)(NU64 x, NU64 k) {
	NU64 result;
	result = (NU64)0;
	result = (NU64)((NU64)((NU64)(x) << (NU64)(k)) | (NU64)((NU64)(x) >> (NU64)((NU64)((NU64)(64ULL) - (NU64)(k)))));
	return result;
}

N_NIMCALL(NU64, next_XD15WiThqxScuoeOixQIfg)(tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg* s) {
	NU64 result;
	NU64 s0;
	NU64 s1;
	NU64 T1_;
	result = (NU64)0;
	s0 = (*s).a0;
	s1 = (*s).a1;
	result = (NU64)((NU64)(s0) + (NU64)(s1));
	s1 = (NU64)(s1 ^ s0);
	T1_ = (NU64)0;
	T1_ = rotl_YUrTkztAwPd2iMVoSj9bYBw(s0, 55ULL);
	(*s).a0 = (NU64)((NU64)(T1_ ^ s1) ^ (NU64)((NU64)(s1) << (NU64)(((NI) 14))));
	(*s).a1 = rotl_YUrTkztAwPd2iMVoSj9bYBw(s1, 36ULL);
	return result;
}

N_NIMCALL(NI, random_F1qFFP53BvbP4L65Kn9bG1w)(NI max) {
	NI result;
{	result = (NI)0;
	{
		while (1) {
			NU64 x;
			x = next_XD15WiThqxScuoeOixQIfg((&state_4atHrcHUZPts5LqH9bzbl0w));
			{
				if (!((NU64)(x) < (NU64)((NU64)((NU64)(18446744073709551615ULL) - (NU64)((NU64)((NU64)(18446744073709551615ULL) % (NU64)(((NU64) (max))))))))) goto LA5_;
				result = ((NI) ((NU64)((NU64)(x) % (NU64)(((NU64) (max))))));
				goto BeforeRet_;
			}
			LA5_: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void) {
	tyObject_RandomGenState_zKRAkOHolLe9c9cWgp3swUJg T1_;
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.a0 = 7616934476015405061ULL;
	T1_.a1 = 15122295919272093642ULL;
	state_4atHrcHUZPts5LqH9bzbl0w = T1_;
}

NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void) {
}

