/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/zero/v/zipf/bak/nimcache/zipf.o /home/zero/v/zipf/bak/nimcache/zipf.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_NIMCALL(NU16, zipf_4fJNs9bl37MvQ0C9cjzR29b1g)(NU16 word);
N_NIMCALL(NI, random_F1qFFP53BvbP4L65Kn9bG1w)(NI max);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, zipfDatInit000)(void);
NI i_VlOjhHw1yxye6UdvEb1Npw;

N_NIMCALL(NU16, zipf_4fJNs9bl37MvQ0C9cjzR29b1g)(NU16 word) {
	NU16 result;
	NI key;
	result = (NU16)0;
	key = random_F1qFFP53BvbP4L65Kn9bG1w(((NI) 27));
	{
		if (!(key == ((NI) 0))) goto LA3_;
		result = word;
	}
	goto LA1_;
	LA3_: ;
	{
		result = zipf_4fJNs9bl37MvQ0C9cjzR29b1g((NU16)((NU32)(word) + (NU32)(((NI) 1))));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_randomDatInit000();
	zipfDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_randomInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	{
		NI res;
		res = ((NI) 0);
		{
			while (1) {
				NU16 T4_;
				NimStringDesc* T5_;
				if (!(res <= ((NI) 900000))) goto LA3;
				i_VlOjhHw1yxye6UdvEb1Npw = res;
				T4_ = (NU16)0;
				T4_ = zipf_4fJNs9bl37MvQ0C9cjzR29b1g(((NU16) 0));
				T5_ = (NimStringDesc*)0;
				T5_ = dollar__rzAI8EMyNBAQwGODeohhAA(((NU64) (T4_)));
				printf("%s\012", T5_? (T5_)->data:"nil");
				fflush(stdout);
				res += ((NI) 1);
			} LA3: ;
		}
	}
}

NIM_EXTERNC N_NOINLINE(void, zipfDatInit000)(void) {
}

